# essai_PyQt
apprentissage de IPython; problèmes de configuration.
si l'on lance     %matplotlib qt   sur l'invite de IPython on reçoit le message d'erreur

File "C:\Users\Allebria\Anaconda3\lib\site-packages\matplotlib\backends\qt_compat.py", line 141 in <module>
 from PyQt4 import QtCore, QtGui
ModuleNotFoundError: No module named 'PyQt4'
